name: bazel
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: mkdir bin
    - name: build
      working-directory: bin
      run: bazel build //...
    - name: test
      working-directory: bin
      run: bazel test //test/...
